### ISSUE TITLE
The Box doesn't assemble

### ISSUE THREAD

**Issue by sharatrp** [kigster/laser-cutter#7] opened 2017-05-03 16:27 UTC
The box formed is impossible to assemble. Any idea why?
Every parameter that was put was default.

Please find the attached file

[makeabox-3.00W-3.00H-3.00D-0.12T-20170503070458.pdf](https://github.com/kigster/laser-cutter/files/974033/makeabox-3.00W-3.00H-3.00D-0.12T-20170503070458.pdf)

**Comment by kigster** [comment] 2017-05-07 05:01
This looks like a duplicate of #6 — your notch is 0.375 which is the same notch that resulted in the problem. 

As a workaround — could you please try leaving the notch value out completely? If that doesn't work, try a couple of different values.

Thanks for reporting it!

**Comment by kigster** [comment] 2017-05-07 05:01
Closing a as dup of #6

**Closed by kigster** 2017-05-07 05:01 UTC
Labels: bug
